Models/ErrorViewModel.cs
using System;

namespace Valence.WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Login/LoginModel.cs
using System.ComponentModel.DataAnnotations;

namespace Valence.WebApp.Models.Login
{
    public class LoginModel
    {
        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Display(Name = "Senha")]
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        public bool RememberLogin { get; set; }
        public string ReturnUrl { get; set; }
    }
}

Controllers/AcessoController.cs
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Valence.WebApp.Models.Login;

namespace Valence.WebApp.Controllers
{
    public class AcessoController : Controller
    {
        private readonly ILogger<AcessoController> _logger;

        public AcessoController(ILogger<AcessoController> logger)
        {
            _logger = logger;
        }
        public IActionResult Login(string ReturnUrl = "/Home/Index")
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToRoute("AbreHome");
            }
            LoginModel objLoginModel = new LoginModel();
            objLoginModel.ReturnUrl = ReturnUrl;
            return View(objLoginModel);
        }

        [Route("/Acesso/Login", Name = "AbreLogin")]
        [HttpPost]
        public IActionResult Login(LoginModel login)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (login.Email == "eronpsn@gmail.com" && login.Password == "1")
                    {
                        _logger.LogInformation("Email " + login.Email + " Senha: " + login.Password);
                        Autenticar(login);
                        _logger.LogInformation("URL: " + login.ReturnUrl);
                        return LocalRedirect(login.ReturnUrl);
                    }
                    else
                    {
                        ViewBag.Message = "Usuário e/ou senha incorretos!";
                    }
                }
            }
            catch (Exception)
            {
                ViewBag.Message = "Ocorreu algum erro ao tentar se logar, tente novamente!";
            }
            return View(login);
        }
        private async void Autenticar(LoginModel login)
        {
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, login.Email),
                new Claim(ClaimTypes.Role, "Usuario_Comum")
            };

            var identidadeDeUsuario = new ClaimsIdentity(claims, "Login");
            ClaimsPrincipal claimPrincipal = new ClaimsPrincipal(identidadeDeUsuario);

            var propriedadesDeAutenticacao = new AuthenticationProperties
            {
                AllowRefresh = true,
                ExpiresUtc = DateTime.Now.ToLocalTime().AddHours(2),
                IsPersistent = true
            };

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimPrincipal, propriedadesDeAutenticacao);
        }
        public async Task<IActionResult> Sair()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToRoute("AbreLogin");
        }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RestSharp;
using Valence.WebApp.Models;
using Microsoft.AspNetCore.Http;
using Valence.WebApp.Models.Login;
using Microsoft.AspNetCore.Authorization;

namespace Valence.WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [Route("/Home/Index", Name = "AbreHome")]
           [Authorize]
       
        public IActionResult Index()
        {
           /* string email = HttpContext.Session.GetString("Email");
            if (string.IsNullOrEmpty(email))
            {
                return RedirectToRoute("AbreLogin");
            }
            ViewBag.Email = email;*/
            return View();
        }


 [Authorize]
        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult Autenticar()
        {
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Acesso/Login.cshtml
@{
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
    ViewData["Title"] = "Login";
    @model Valence.WebApp.Models.Login.LoginModel 
}
  <!-- /.login-logo -->
  <div class="card card-outline card-primary">
    <div class="card-header text-center">
      <a href="#" class="h1"><b>Admin</b>LTE</a>
    </div>
    <div class="card-body">
      <p class="login-box-msg">Dados de acesso</p>
 @if (!string.IsNullOrEmpty(ViewBag.Message))
            {
                <span class="text-danger">
                    @ViewBag.Message
                </span>
            }
      <form asp-controller="Acesso" asp-action="Login" method="post">
        <div class="input-group mb-3">
           @Html.HiddenFor(x => x.ReturnUrl)
          <input asp-for="Email" type="email" class="form-control" placeholder="Email">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input asp-for="Password" type="password" class="form-control" placeholder="Senha">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="remember">
              <label for="remember">
                Lembre-me
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Acessar</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

    <!-- /.card-body -->
      </div>
<script src="~/lib/jquery/dist/jquery.min.js"></script> 

      <script>

         $(function () {
          new PNotify({
                                  title: 'Regular Success',
                                  text: 'That thing that you were trying to do worked!',
                                  type: 'success',
                                  styling: 'bootstrap3',
                                  delay: 3000,
                                  
                              });
        });
      </script>

Views/Home/Autenticar.cshtml
@{
    ViewData["Title"] = "Autenticar";
}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Desire2Learn Auth SDK Sample</title>
	<style type = "text/css">
		table.plain
		{
		  border-color: transparent;
		  border-collapse: collapse;
		}

		table td.plain
		{
		  padding: 5px;
		  border-color: transparent;
		}

		table th.plain
		{
		  padding: 6px 5px;
		  text-align: left;
		  border-color: transparent;
		}

		tr:hover
		{
			background-color: transparent !important;
		}

		.error
		{
			color: #FF0000;
		}
	</style>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type = "text/javascript"></script>

</head>
<body onload="init()">
	<input type="button" name="authBtn" value="Load Defaults" id="resetButton" onclick="defaults()"/>
	<hr />
	<table>
		<tr>
			<td>
				<b>Host: </b>
			</td>
			<td>
				<input name="hostField" type="text" style="width:20em" value="" id="hostField" />
			</td>
			<td>
				<b>Port:</b>
			</td>
			<td>
				<input name="portField" type="text" style="width:20em" value="" id="portField" />
			</td>
			<td>
				<input id="schemeField" type="checkbox" name="schemeField" checked="true" />
				HTTPS
			</td>
		</tr>
		<tr>
			<td>
				<b>App ID:</b>
			</td>
			<td>
				<input name="appIdField" type="text" style="width:20em" value="" id="appIdField" />
			</td>
			<td>
				<b>App Key:</b>
			</td>
			<td>
				<input name="appKeyField" type="text" style="width:20em" value="" id="appKeyField" />
			</td>
		</tr>
	</table>
	<div id="userDiv">
		<br />
		<span>This information is returned by the authentication server and is valid only for this application:</span>
		<table>
			<tr>
				<td>
					<b>User ID:</b>
				</td>
				<td>
					<input name="userIdField" type="text" style="width:20em" id="userIdField" />
				</td>
			</tr>
			<tr>
				<td>
					<b>User Key:</b>
				</td>
				<td>
					<input name="userKeyField" type="text" style="width:20em" id="userKeyField" />
				</td>
			</tr>
		</table>
		<input type="button" name="authBtn" value="Deauthenticate" id="deauthButton" onclick="deauthenticate()">
	</div>
	<span id="authNotice">Note: to authenticate against the test server, you can user username
						  "sampleapiuser" and password "Tisabiiif".
	</span><br />
	<input type="button" name="authBtn" value="Authenticate" id="authenticateButton" onclick="authenticateUser(); ui()"/><br />
    <input type="button" id="manualBtn" value="Manually set credentials" onclick="setCredentials()" />
    <input type="button" name="authBtn" value="Save" id="manualAuthBtn" hidden=true onclick="saveCredentials()"/>

	<hr />
	<table>
		<tr>
			<td>
				<b>Examples:</b>
			</td>
			<td>
				<button type="button" onclick="exampleGetVersions()">
					Get Versions</button>
			</td>
		</tr>
		<tr>
			<td>
			</td>
			<td>
				<button type="button" onclick="exampleWhoAmI()">
					WhoAmI</button>
			</td>
		</tr>
		<tr>
			<td></td>
			<td>
				<button type="button" onclick="exampleCreateUser()">
					Create User</button>
			</td>
		</tr>
	</table>
	<br />
	<b>Method:</b>&nbsp;
	<input value="GET" name="method" type="radio" id="GETField" onclick="hideData()" />GET
	&nbsp;
	<input value="POST" name="method" type="radio" id="POSTField" onclick="showData()" />POST
    &nbsp;
    <input value="PUT" name="method" type="radio" id="PUTField" onclick="showData()" />PUT
    &nbsp;
    <input value="DELETE" name="method" type="radio" id="DELETEField" onclick="hideData()" />DELETE<br />
	<b>Action:</b>&nbsp;<input name="actionField" type="text" id="actionField" style="width:600px;" /><br />
	<b id="dataFieldLabel">Data:</b><br />
	<textarea name="dataField" rows="2" cols="20" id="dataField" style="height:400px;width:600px;">
</textarea><br />
	<b id="responseFieldLabel" hidden="false">Response:</b><br />
	<textarea name="responseField" hidden="false" rows="2" cols="20" id="responseField" style="height:400px;width:600px;">
</textarea><br />
	<input type="button" name="submitButton" value="Submit" id="submitButton" onclick="doAPIRequest()"/>

</body>
<script type="text/javascript">
	function deleteAllCookies() {
		var cookies = document.cookie.split(";");

		for (var i = 0; i < cookies.length; i++) {
			var cookie = cookies[i];
			var eqPos = cookie.indexOf("=");
			var name = eqPos > -1 ? cookie.substr(0, eqPos) : cookie;
			document.cookie = name + "=;expires=Thu, 01 Jan 1970 00:00:00 GMT";
		}
	}

	function setCookie(obj) {
		deleteAllCookies();
		document.cookie = "GettingStartedSettings=" + escape(JSON.stringify(obj));
	}

	function getCookie() {
		var obj = {}
		try {
			cookie = document.cookie.match(/GettingStartedSettings=[^;]*;?/)[0].replace(/[^=]*=/, '').replace(/;?\ *$/, '');
			obj = JSON.parse(unescape(cookie));
		} catch(e) {
			// ignore
		}
		return obj;
	}

	function showData() {
		document.getElementById("dataFieldLabel").hidden = false;
		document.getElementById("dataField").hidden=false;
	}

	function hideData() {
		document.getElementById("dataFieldLabel").hidden = true;
		document.getElementById("dataField").hidden=true;
	}

	function exampleGetVersions() {
		hideData();
		document.getElementById("GETField").checked = true;
		document.getElementById("actionField").value = "/d2l/api/versions/";
	}

	function exampleWhoAmI() {
		hideData();
		document.getElementById("GETField").checked = true;
		document.getElementById("actionField").value = "/d2l/api/lp/1.0/users/whoami";
	}

    function exampleCreateUser() {
        showData();
        document.getElementById("POSTField").checked = true;
        document.getElementById("actionField").value = "/d2l/api/lp/1.0/users/";
        document.getElementById("dataField").value = "{\n  \"OrgDefinedId\": \"<string>\",\n  \"FirstName\": \"<string>\",\n  \"MiddleName\": \"<string>\",\n  \"LastName\": \"<string>\",\n  \"ExternalEmail\": \"<string>|null\",\n  \"UserName\": \"<string>\",\n  \"RoleId\": \"<number>\",\n  \"IsActive\": \"<boolean>\",\n  \"SendCreationEmail\": \"<boolean>\"\n}";
    }

    function setCredentials() {
        document.getElementById("manualAuthBtn").hidden = false;
        document.getElementById("deauthButton").hidden = true;
        document.getElementById("userDiv").hidden = false;
        document.getElementById("userIdField").hidden = false;
        document.getElementById("userKeyField").hidden = false;
        document.getElementById("manualBtn").hidden = true;
        document.getElementById("authenticateButton").hidden = true;
        document.getElementById("authNotice").hidden = true;
    }

	function saveCredentials() {
		var values = getCookie();
		values.userId = document.getElementById("userIdField").value;
		values.userKey = document.getElementById("userKeyField").value;
		setCookie(values);
		window.location.replace('index.html');
	}

	function ui() {
		hideData();
		if(document.getElementById("userIdField").value === "") document.getElementById("userIdField").value = localStorage.userId || "";
		if(document.getElementById("userKeyField").value === "") document.getElementById("userKeyField").value = localStorage.userKey || "";
		if(document.getElementById("userIdField").value !== "") {
			document.getElementById("userIdField").disabled = true;
			document.getElementById("userKeyField").disabled = true;
			document.getElementById("manualBtn").hidden = true;
			document.getElementById("authenticateButton").hidden = true;
			document.getElementById("authNotice").hidden = true;
			document.getElementById("hostField").disabled = true;
			document.getElementById("portField").disabled = true;
			document.getElementById("appKeyField").disabled = true;
			document.getElementById("appIdField").disabled = true;
		} else {
			document.getElementById("userIdField").hidden = true;
			document.getElementById("userKeyField").hidden = true;
			document.getElementById("userDiv").hidden = true;
			document.getElementById("hostField").disabled = false;
			document.getElementById("portField").disabled = false;
			document.getElementById("appKeyField").disabled = false;
			document.getElementById("appIdField").disabled = false;
		}
	}

	function defaults() {
		setCookie({});
		window.location.replace('index.html');
	}

	function init() {
		var values = getCookie();
		if(typeof values.host == 'undefined' || values.host === '') values.host = "ava.grupotiradentes.com";
		if(typeof values.port == 'undefined' || values.port === '') values.port = 443;
		if(typeof values.scheme == 'undefined' || values.scheme === '') values.scheme = "https";
		if(typeof values.appId == 'undefined' || values.appId === '') values.appId = "iWAAJYnl0IMj9CM94T8A3w";
		if(typeof values.appKey == 'undefined' || values.appKey === '') values.appKey = "TrHRH1CvZUccEeQUp5Ufvg";
		setCookie(values);

		document.getElementById("hostField").value = values.host;
		document.getElementById("portField").value = values.port;
		document.getElementById("schemeField").checked = ( values.scheme === "https" );
		document.getElementById("appIdField").value = values.appId;
		document.getElementById("appKeyField").value = values.appKey;

		ui();
	}
</script>
</html>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<p>@ViewBag.Email</p>

Views/Home/NeedsAuth.cshtml
@{
    ViewData["Title"] = "NeedsAuth";
}

<!DOCTYPE html>

<html>
    <head>
        <title>Basic Demo App - Login required</title>
    </head>
    <body>
        <p>You must first log into your Brightspace LMS, and ensure that you register this application in Manage Extensibility as an ID-Key application.</p>
        <p>Then, provision the Web.config file with the App ID, App Key, and domain name of your Brightspace host. Once so provisioned, you can use the ID-Key authentication workflow to authenticate an LMS user for testing with this app.</p>
        <p>If you have already authenticated with the LMS you will not need to enter your password to re-login with this app. To force a global logout, log in and log out of the LMS manually.</p>
        <a href="@ViewBag.valenceAuthUrl">Log in</a>
    </body>
</html>

Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Valence.WebApp</title>
    <link rel="stylesheet" href="~/login/fontawesome-free/css/all.min.css" />
    <link rel="stylesheet" href="~/login/icheck-bootstrap/icheck-bootstrap.min.css" />
    <link rel="stylesheet" href="~/login/css/adminlte.min.css" />

        <!-- PNotify -->
    <link href="~/vendors/pnotify/dist/pnotify.css" rel="stylesheet">
    <link href="~/vendors/pnotify/dist/pnotify.buttons.css" rel="stylesheet">
    <link href="~/vendors/pnotify/dist/pnotify.nonblock.css" rel="stylesheet">
</head>
<body class="hold-transition login-page">
    <div class="login-box">
            @RenderBody()
    </div>
   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/login/js/adminlte.min.js"></script>

        <!-- PNotify -->
    <script src="~/vendors/pnotify/dist/pnotify.js"></script>
    <script src="~/vendors/pnotify/dist/pnotify.buttons.js"></script>
    <script src="~/vendors/pnotify/dist/pnotify.nonblock.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>